### ISSUE TITLE
Warning regarding refs in dropdown menu trigger

### ISSUE THREAD

**Issue by alasdairwilson** [OxfordRSE/gutenberg#119]
This warning causes exception on a paragraph test, I have bypassed that excception for now but we will need to revisit.

I am not entirely sure how we can, I believe the issue might actually  be in flowbite; motivation for a swap to material #118

I am not 100% sure that it is a flowbite issue though.

```
client.js:1 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Trigger`.
    at TinyButton (webpack-internal:///./components/content/Thread.tsx:47:11)
    at Trigger (webpack-internal:///./node_modules/flowbite-react/lib/esm/components/Dropdown/Dropdown.js:36:20)
    at DropdownComponent (webpack-internal:///./node_modules/flowbite-react/lib/esm/components/Dropdown/Dropdown.js:51:30)
    at div
    at Stack (webpack-internal:///./components/ui/Stack.tsx:9:11)
    at div
    at div
    at div
    at Thread (webpack-internal:///./components/content/Thread.tsx:111:11)
    at div
    at div
    at div
    at Paragraph (webpack-internal:///./components/content/Paragraph.tsx:36:11)
    at p (webpack-internal:///./components/content/Content.tsx:61:15)
    at ReactMarkdown (webpack-internal:///./node_modules/react-markdown/lib/react-markdown.js:88:42)
    at div
    at Content (webpack-internal:///./components/content/Content.tsx:236:11)
    at main
    at div
    at RecoilRoot_INTERNAL (webpack-internal:///./node_modules/recoil/es/index.js:4473:3)
    at RecoilRoot (webpack-internal:///./node_modules/recoil/es/index.js:4639:5)
    at Layout (webpack-internal:///./components/Layout.tsx:31:11)
    at SectionComponent (webpack-internal:///./pages/material/[themeId]/[courseId]/[sectionId].tsx:15:11)
    at f (webpack-internal:///./node_modules/next-themes/dist/index.module.js:8:597)
    at $ (webpack-internal:///./node_modules/next-themes/dist/index.module.js:8:348)
    at ContextProvider (webpack-internal:///./lib/context/ContextProvider.tsx:32:11)
    at SessionProvider (webpack-internal:///./node_modules/next-auth/react/index.js:455:24)
    at MyApp (webpack-internal:///./pages/_app.tsx:23:11)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:79:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:5389)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:7785)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:78:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:182:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:396:11)
    ```

**Comment by alasdairwilson** [comment]
Closed as completed
